### ISSUE TITLE
EgocentricFood Dataset

### ISSUE THREAD

**Issue by ZoulfikarShmayssani** [mksarker/FoodPlaces#1]
Hello,

Can you provide me with a link for the used dataset ( The one you provided says 404 Not Found).

Thank you in advance.

**Comment by mksarker** [comment]
Hi,
Since, I have uploaded some free webspace, now its closed. Sorry, its quite large dataset and not able to post in GitHub.

**Comment by ZoulfikarShmayssani** [comment]
Hello,

Can you upload it to Google Drive and share the link with me? Or can you please point me to the online dataset? I will be very grateful for that.

Thanks in advance

**Comment by mksarker** [comment]
Here you can find the dataset, http://www.ub.edu/cvub/dataset/
